language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
script: 
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then unit2 discover test; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then python -m unittest discover; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then python -m unittest discover; fi
branches:
  only:
    - master
    - devel
